#!/bin/bash
#SBATCH --job-name=cartagene_umap
#SBATCH --account=
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --mem=16G
#SBATCH --time 06:00:00
#SBATCH --error=cartagene/logs/%x-%j.out
#SBATCH --out=cartagene/logs/%x-%j.err

##############################################################################
# Same as the array-based job, but only in 2D or 3D so we don't need arrays. #
##############################################################################

# For array jobs we can't overwrite environments.
ENVDIR=cartagene/env

source ${ENVDIR}/bin/activate

PC_ARRAY=(5 10 25 50)
NN_ARRAY=(10 15 25)
MD_ARRAY=(0.3 0.5)
NC=3

D_SET=cartagene/data/hla_removed_ld_thinned.eigenvec
OUT_DIR=cartagene/projections_viz/hla_removed_ld_thinned_0.1
LOG_DIR=cartagene/logs

# Specify whether the source file has headers
HEADER=F

for pc in "${PC_ARRAY[@]}"
        do
        for nn in "${NN_ARRAY[@]}"
                do
                for md in "${MD_ARRAY[@]}"
                        do
                                python cartagene/code/clustering/general_umap_script.py \
                                        -dset $D_SET \
                                        -pc $pc \
                                        -nn $nn \
                                        -md $md \
                                        -nc ${NC} \
                                        -outdir $OUT_DIR \
                                        -head $HEADER \
                                        -log $LOG_DIR

                        done
                done
        done

deactivate
